services:
  app:
    command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next

  db:
    ports:
      - '${DB_PORT}:5432'
