services:
  vylety:
    image: node:22.17-alpine
    ports:
      - '3000:3000'
    volumes:
      - ./data/app:/home/node/app
      - ./data/node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - vylety-db
    env_file:
      - .env

  vylety-db:
    restart: always
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
